# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  RESOURCE_GROUP: 'DAAS-DevOps-Testing'
  GitRepoAspNet: https://github.com/puneetg1983/WebCampGit

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: 'b2430cf7-78c0-440a-aa4a-a25665c5778e'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PublishProfile=FolderProfile.pubxml /p:PackageAsSingleFile=true /p:publishUrl="$(build.artifactStagingDirectory)\\"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  displayName: 'Delete additional files'
  inputs:
    targetType: 'inline'
    script: |
      Remove-Item -Recurse -Force $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\Configuration -Verbose
      Remove-Item -Recurse -Force $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\DiagnosticTools -Verbose
      Remove-Item -Recurse -Force $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\bin\amd64 -Verbose
      Remove-Item -Recurse -Force $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\bin\staticcontent -Verbose
      Remove-Item -Recurse -Force $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\bin\x64 -Verbose
      Remove-Item -Recurse -Force $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\bin\x86 -Verbose
      Remove-Item -Recurse -Force $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\bin\DiagnosticAnalysis -Verbose
      Remove-Item $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\bin\* -include *.ps1, *.html -Verbose
      Remove-Item $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\bin\Dia2Lib.dll -Verbose
      Remove-Item $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\bin\OSExtensions.dll -Verbose
      Remove-Item $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\bin\TraceReloggerLib.dll -Verbose
      
      $fileVersion = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("$Env:BUILD_ARTIFACTSTAGINGDIRECTORY\bin\daas.dll").FileVersion
      $fileVersion
      
      Write-Host "##vso[task.setvariable variable=DAAS_VERSION]$fileVersion"

      $uniqueSiteName = "daasdevops" + (Get-Date -Format "yyyyMMdd-hhmm")
      Write-Host "##vso[task.setvariable variable=SITE_NAME]$uniqueSiteName"

- task: ArchiveFiles@2
  displayName: 'Create Daas Site Extension Zip file'
  inputs:
    rootFolderOrFile: '$(build.artifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/DaaS_$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      md $Env:AGENT_BUILDDIRECTORY\Temp\SiteExt
      Copy-Item -Path $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\DaaS_$Env:BUILD_BUILDID.zip -Destination $Env:AGENT_BUILDDIRECTORY\Temp\SiteExt\DaaS_$Env:BUILD_BUILDID.zip -Verbose
      
      Write-Host Cleaning up ARTIFACTSTAGINGDIRECTORY
      Remove-Item -Recurse -Force $Env:BUILD_ARTIFACTSTAGINGDIRECTORY -Verbose
      
      md $Env:BUILD_ARTIFACTSTAGINGDIRECTORY
      Copy-Item -Path $Env:AGENT_BUILDDIRECTORY\Temp\SiteExt\DaaS_$Env:BUILD_BUILDID.zip -Destination $Env:BUILD_ARTIFACTSTAGINGDIRECTORY\DaaS_$Env:BUILD_BUILDID.zip 
      Write-Host FileVersion is $Env:DAAS_VERSION
    failOnStderr: true
    showWarnings: true

- task: AzurePowerShell@5
  displayName: 'Setup New Web-App'
  inputs:
    azureSubscription: 'Private Test Sub PUNEETG(6b6db65f-680e-4650-b97d-e82ed6a0f583)'
    ScriptType: 'InlineScript'
    Inline: |
      $resources = az resource list --resource-group $Env:RESOURCE_GROUP | ConvertFrom-Json
      Write-Host "Deleting Web Apps..."
      foreach ($resource in $resources) {
        if ($resource.id -like '*/providers/Microsoft.Web/sites/*') {
          Write-Host $("  Deleting " + $resource.id)
          az resource delete --resource-group $Env:RESOURCE_GROUP --ids $resource.id --verbose
          }
        }
        Write-Host "Deleting App Service Plans"
        foreach ($resource in $resources) {
          if ($resource.id -like '*/providers/Microsoft.Web/serverfarms/*') {
            Write-Host $("  Deleting " + $resource.id)
            az resource delete --resource-group $Env:RESOURCE_GROUP --ids $resource.id --verbose
          }
        }

      Write-Host "Creating App Service Plan"
      az appservice plan create --name $Env:SITE_NAME --resource-group $Env:RESOURCE_GROUP --sku B1
      
      Write-Host "Creating Web App"
      az webapp create --name $Env:SITE_NAME --resource-group $Env:RESOURCE_GROUP --plan $Env:SITE_NAME
      az webapp config set --resource-group $Env:RESOURCE_GROUP --name $Env:SITE_NAME --always-on true
      
      Write-Host "Adding MSBuild App Setting"
      az webapp config appsettings set --resource-group $Env:RESOURCE_GROUP --name $Env:SITE_NAME --settings MSBUILD_PATH=%MSBUILD_15_DIR%\\msbuild.exe

      Write-Host "Setting up Github for $Env:SITE_NAME"
      az webapp deployment source config --name $Env:SITE_NAME --resource-group $Env:RESOURCE_GROUP --repo-url $Env:GitRepoAspNet --branch master --manual-integration

      Write-Host "Getting Publish Profiler"
      $publishProfileString = Invoke-AzureRmResourceAction -ResourceGroupName $Env:RESOURCE_GROUP `
        -ResourceType Microsoft.Web/sites `
        -ResourceName $Env:SITE_NAME `
        -Action publishxml `
        -ApiVersion 2015-08-01 -Force

      $publishProfileXml =[xml]$publishProfileString
      $userName = $publishProfileXml.publishData.publishProfile[0].userName
      $password = $publishProfileXml.publishData.publishProfile[0].userPWD

      Write-Host ("UserName is " + $userName)

    azurePowerShellVersion: 'LatestVersion'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: drop

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
